name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build

      - name: Generate JaCoCo reports
        run: ./gradlew jacocoTestReport

      - name: Generate JaCoCo root reports
        run: ./gradlew jacocoRootReport

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: 'build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml'

      - name: Upload reports to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew jacocoTestReport jacocoRootReport coverallsJacoco

      - name: Upload reports to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info
